-- MySQL Script generated by MySQL Workbench
-- Sun Nov  2 18:44:01 2025
-- Model: New Model    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`usuario` (
  `nombre` VARCHAR(20) NOT NULL,
  `fecha_nac` DATE NULL,
  `gmail` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `fecha_registro` DATETIME NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `gmail_UNIQUE` (`gmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `ultima_conexion` TIME NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`admin_id`, `usuario_id_usuario`),
  INDEX `fk_admin_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_admin_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `restaurante`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `preferencias` VARCHAR(200) NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `usuario_id_usuario`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `restaurante`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`telefono` (
  `id_telefono` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_telefono`, `cliente_cliente_id`),
  INDEX `fk_telefono_cliente1_idx` (`cliente_cliente_id` ASC),
  CONSTRAINT `fk_telefono_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `restaurante`.`cliente` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`empleado_id`, `usuario_id_usuario`),
  INDEX `fk_empleado_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_empleado_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `restaurante`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`promocion` (
  `promocion_id` INT NOT NULL AUTO_INCREMENT,
  `condiciones` VARCHAR(10) NULL,
  `duracion` DATE NULL,
  `titulo` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(10) NULL,
  `tipo` ENUM('descuento', '2x1', 'combo', 'cumpleaños') NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`promocion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `estado` ENUM('pendiente', 'confirmada', 'cancelada', 'completada') NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `cliente_cliente_id`),
  INDEX `fk_reserva_cliente1_idx` (`cliente_cliente_id` ASC),
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `restaurante`.`cliente` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`mesa` (
  `mesa_id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `numero` INT NOT NULL,
  `estado` ENUM('disponible', 'ocupada', 'reservada', 'mantenimiento') NOT NULL,
  `fecha_asig` DATE NOT NULL,
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('recibido', 'preparacion', 'listo', 'entregado', 'cancelado') NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `mesa_mesa_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `mesa_mesa_id`),
  INDEX `fk_pedido_mesa1_idx` (`mesa_mesa_id` ASC),
  CONSTRAINT `fk_pedido_mesa1`
    FOREIGN KEY (`mesa_mesa_id`)
    REFERENCES `restaurante`.`mesa` (`mesa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NOT NULL,
  `estado` ENUM('disponible', 'no_disponible') NOT NULL,
  `admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`id_menu`, `admin_admin_id`),
  INDEX `fk_menu_admin1_idx` (`admin_admin_id` ASC),
  CONSTRAINT `fk_menu_admin1`
    FOREIGN KEY (`admin_admin_id`)
    REFERENCES `restaurante`.`admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`plato` (
  `plato_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `menu_id menu` INT NOT NULL,
  `imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`plato_id`, `menu_id menu`),
  INDEX `fk_plato_menu1_idx` (`menu_id menu` ASC),
  CONSTRAINT `fk_plato_menu1`
    FOREIGN KEY (`menu_id menu`)
    REFERENCES `restaurante`.`menu` (`id_menu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`stock` (
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  `unidad_medida` VARCHAR(45) NULL,
  `cantidad_total` INT NULL,
  `ultima_actu` DATE NULL,
  PRIMARY KEY (`stock_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` INT NOT NULL,
  `tipo` VARCHAR(30) NULL,
  `admin_admin_id` INT NOT NULL,
  `stock_stock_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `admin_admin_id`, `stock_stock_id`),
  INDEX `fk_producto_admin1_idx` (`admin_admin_id` ASC),
  INDEX `fk_producto_stock1_idx` (`stock_stock_id` ASC),
  CONSTRAINT `fk_producto_admin1`
    FOREIGN KEY (`admin_admin_id`)
    REFERENCES `restaurante`.`admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_stock1`
    FOREIGN KEY (`stock_stock_id`)
    REFERENCES `restaurante`.`stock` (`stock_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`historial` (
  `historial_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `tipo_movimiento` ENUM('entrada', 'salida', 'ajuste') NULL,
  `cantidad` INT NULL,
  `fecha` DATE NULL,
  `stock_id stock` INT NOT NULL,
  `admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`historial_id`, `stock_id stock`, `admin_admin_id`),
  INDEX `fk_historial_stock1_idx` (`stock_id stock` ASC),
  INDEX `fk_historial_admin1_idx` (`admin_admin_id` ASC),
  CONSTRAINT `fk_historial_stock1`
    FOREIGN KEY (`stock_id stock`)
    REFERENCES `restaurante`.`stock` (`stock_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_historial_admin1`
    FOREIGN KEY (`admin_admin_id`)
    REFERENCES `restaurante`.`admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`registro de visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`registro de visita` (
  `id_visita` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME(3) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_visita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`pedido_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`pedido_detalle` (
  `pedido_pedido_id` INT NOT NULL,
  `plato_plato_id` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`pedido_pedido_id`, `plato_plato_id`),
  INDEX `fk_pedido_detalle_plato1_idx` (`plato_plato_id` ASC),
  CONSTRAINT `fk_pedido_detalle_pedido1`
    FOREIGN KEY (`pedido_pedido_id`)
    REFERENCES `restaurante`.`pedido` (`pedido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_detalle_plato1`
    FOREIGN KEY (`plato_plato_id`)
    REFERENCES `restaurante`.`plato` (`plato_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`mesa_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`mesa_cliente` (
  `mesa_mesa_id` INT NOT NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`mesa_mesa_id`, `cliente_cliente_id`),
  INDEX `fk_mesa_has_cliente_cliente1_idx` (`cliente_cliente_id` ASC),
  INDEX `fk_mesa_has_cliente_mesa1_idx` (`mesa_mesa_id` ASC),
  CONSTRAINT `fk_mesa_has_cliente_mesa1`
    FOREIGN KEY (`mesa_mesa_id`)
    REFERENCES `restaurante`.`mesa` (`mesa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mesa_has_cliente_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `restaurante`.`cliente` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`promo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`promo_cliente` (
  `promocion_promocion_id` INT NOT NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`promocion_promocion_id`, `cliente_cliente_id`),
  INDEX `fk_promocion_has_cliente_cliente1_idx` (`cliente_cliente_id` ASC),
  INDEX `fk_promocion_has_cliente_promocion1_idx` (`promocion_promocion_id` ASC),
  CONSTRAINT `fk_promocion_has_cliente_promocion1`
    FOREIGN KEY (`promocion_promocion_id`)
    REFERENCES `restaurante`.`promocion` (`promocion_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_promocion_has_cliente_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `restaurante`.`cliente` (`cliente_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`mesa_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`mesa_empleado` (
  `mesa_mesa_id` INT NOT NULL,
  `empleado_empleado_id` INT NOT NULL,
  PRIMARY KEY (`mesa_mesa_id`, `empleado_empleado_id`),
  INDEX `fk_mesa_has_empleado_empleado1_idx` (`empleado_empleado_id` ASC),
  INDEX `fk_mesa_has_empleado_mesa1_idx` (`mesa_mesa_id` ASC),
  CONSTRAINT `fk_mesa_has_empleado_mesa1`
    FOREIGN KEY (`mesa_mesa_id`)
    REFERENCES `restaurante`.`mesa` (`mesa_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mesa_has_empleado_empleado1`
    FOREIGN KEY (`empleado_empleado_id`)
    REFERENCES `restaurante`.`empleado` (`empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;